python offloading_client.py input_20.tgff cpop
python offloading_client.py input_30.tgff cpop
python offloading_client.py input_40.tgff cpop
python offloading_client.py input_50.tgff cpop
python offloading_client.py input_60.tgff cpop
python offloading_client.py input_70.tgff cpop
python offloading_client.py input_80.tgff cpop
python offloading_client.py input_90.tgff cpop
python offloading_client.py input_100.tgff cpop
python offloading_client.py input_110.tgff cpop
